# Generated by Django 6.0.5 on 2026-06-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="Employee",
        ),
    ]
